# Generated by Django 4.2.1 on 2023-07-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_update_models2'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='guias',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='contenido',
            field=models.TextField(max_length=200),
        ),
    ]
